name: dictionary
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  firebase_auth: ^5.3.1
  url_launcher: ^6.2.12
  pdf: ^3.10.8
  printing: ^5.13.1
  flutter_email_sender: ^6.0.3
  sqflite: ^2.4.1
  path: ^1.9.0
  shared_preferences: ^2.1.1
  logger: ^2.3.0
  intl: ^0.18.1
  share_plus: ^12.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.12.0

flutter_icons:
  uses-material-design: true
  android: true
  ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true

  assets:
    - assets/app_icon.png
    - assets/aaa.jpg
    - assets/bangla_words.db
    - assets/english_words.db

  fonts:
    - family: NotoSansBengali
      fonts:
        - asset: assets/fonts/NotoSansBengali-Regular.ttf
        - asset: assets/fonts/NotoSansBengali-Bold.ttf
          weight: 700
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
